DROP DATABASE IF EXISTS EloyCon;
CREATE DATABASE EloyCon;

USE EloyCon;

CREATE TABLE traducciones(
    id INT AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(50) NOT NULL,
    es VARCHAR(1500) NOT NULL,
    en VARCHAR(1500) NOT NULL
);