INSERT INTO imagenes_proyectos (url, tipo, id_proyecto) VALUES 
('app/static/img/home-projects/construction/project-1/facadesA.webp', 'fachada', 1),
('app/static/img/home-projects/construction/project-1/fenceA.webp', 'cerca', 1),
('app/static/img/home-projects/construction/project-1/fenceB.webp', 'cerca', 1),
('app/static/img/home-projects/construction/project-1/living-roomA.webp', 'sala de estar', 1),
('app/static/img/home-projects/construction/project-1/living-roomB.webp', 'sala de estar', 1),
('app/static/img/home-projects/construction/project-1/living-roomC.webp', 'sala de estar', 1),
('app/static/img/home-projects/construction/project-1/roomA.webp', 'dormitorio', 1),
('app/static/img/home-projects/construction/project-1/roomB.webp', 'dormitorio', 1),
('app/static/img/home-projects/construction/project-1/roomC.webp', 'dormitorio', 1),
('app/static/img/home-projects/construction/project-1/roomD.webp', 'dormitorio', 1),
('app/static/img/home-projects/construction/project-1/stairsA.webp', 'escaleras', 1),
('app/static/img/home-projects/construction/project-1/stairsB.webp', 'escaleras', 1),
('app/static/img/home-projects/construction/project-1/terraceA.webp', 'terraza', 1),
('app/static/img/home-projects/construction/project-1/terraceB.webp', 'terraza', 1),
('app/static/img/home-projects/construction/project-1/terraceC.webp', 'terraza', 1),
('app/static/img/home-projects/construction/project-2/bathroomA.webp', 'baño', 2),
('app/static/img/home-projects/construction/project-2/bathroomB.webp', 'baño', 2),
('app/static/img/home-projects/construction/project-2/facadesA.webp', 'fachada', 2),
('app/static/img/home-projects/construction/project-2/fenceA.webp', 'cerca', 2),
('app/static/img/home-projects/construction/project-2/fenceB.webp', 'cerca', 2),
('app/static/img/home-projects/construction/project-2/fenceC.webp', 'cerca', 2),
('app/static/img/home-projects/construction/project-2/garageA.webp', 'garaje', 2),
('app/static/img/home-projects/construction/project-2/garageB.webp', 'garaje', 2),
('app/static/img/home-projects/construction/project-2/garageC.webp', 'garaje', 2),
('app/static/img/home-projects/construction/project-2/gymA.webp', 'gym', 2),
('app/static/img/home-projects/construction/project-2/gymB.webp', 'gym', 2),
('app/static/img/home-projects/construction/project-2/gymC.webp', 'gym', 2),
('app/static/img/home-projects/construction/project-2/movie-theaterA.webp', 'sala de cine', 2),
('app/static/img/home-projects/construction/project-2/movie-theaterB.webp', 'sala de cine', 2),
('app/static/img/home-projects/construction/project-2/movie-theaterC.webp', 'sala de cine', 2),
('app/static/img/home-projects/construction/project-2/terraceA.webp', 'terraza', 2),
('app/static/img/home-projects/construction/project-2/terraceB.webp', 'terraza', 2),
('app/static/img/home-projects/construction/project-3/barbecue-areaA.webp', 'area de barbacoa', 3),
('app/static/img/home-projects/construction/project-3/barbecue-areaB.webp', 'area de barbacoa', 3),
('app/static/img/home-projects/construction/project-3/barbecue-areaC.webp', 'area de barbacoa', 3),
('app/static/img/home-projects/construction/project-3/fachadaA.webp', 'fachada', 3),
('app/static/img/home-projects/construction/project-3/laundry-roomA.webp', 'zona de lavado', 3),
('app/static/img/home-projects/construction/project-3/laundry-roomB.webp', 'zona de lavado', 3),
('app/static/img/home-projects/construction/project-3/laundry-roomC.webp', 'zona de lavado', 3),
('app/static/img/home-projects/construction/project-3/patioA.webp', 'patio', 3),
('app/static/img/home-projects/construction/project-3/patioB.webp', 'patio', 3),
('app/static/img/home-projects/construction/project-3/patioC.webp', 'patio', 3),
('app/static/img/home-projects/construction/project-3/pondA.webp', 'estanque', 3),
('app/static/img/home-projects/construction/project-3/pondB.webp', 'estanque', 3),
('app/static/img/home-projects/construction/project-4/facadesA.webp', 'fachada', 4),
('app/static/img/home-projects/construction/project-4/living-roomA.webp', 'sala de estar', 4),
('app/static/img/home-projects/construction/project-4/living-roomB.webp', 'sala de estar', 4),
('app/static/img/home-projects/construction/project-4/playgroundA.webp', 'patio de niños', 4),
('app/static/img/home-projects/construction/project-4/playgroundB.webp', 'patio de niños', 4),
('app/static/img/home-projects/construction/project-4/playgroundC.webp', 'patio de niños', 4),
('app/static/img/home-projects/construction/project-4/pondA.webp', 'estanque', 4),
('app/static/img/home-projects/construction/project-4/pondB.webp', 'estanque', 4),
('app/static/img/home-projects/construction/project-4/pondC.webp', 'estanque', 4),
('app/static/img/home-projects/construction/project-4/poolA.webp', 'piscina', 4),
('app/static/img/home-projects/construction/project-4/poolB.webp', 'piscina', 4),
('app/static/img/home-projects/construction/project-4/poolC.webp', 'piscina', 4),
('app/static/img/home-projects/construction/project-4/terraceA.webp', 'terraza', 4),
('app/static/img/home-projects/construction/project-4/terraceB.webp', 'terraza', 4),
('app/static/img/home-projects/construction/project-4/terraceC.webp', 'terraza', 4),
('app/static/img/home-projects/construction/project-5/facadesA.webp', 'fachada', 5),
('app/static/img/home-projects/construction/project-5/gymA.webp', 'gym', 5),
('app/static/img/home-projects/construction/project-5/gymB.webp', 'gym', 5),
('app/static/img/home-projects/construction/project-5/gymC.webp', 'gym', 5),
('app/static/img/home-projects/construction/project-5/kitchenA.webp', 'cocina', 5),
('app/static/img/home-projects/construction/project-5/kitchenB.webp', 'cocina', 5),
('app/static/img/home-projects/construction/project-5/kitchenC.webp', 'cocina', 5),
('app/static/img/home-projects/construction/project-5/living-roomA.webp', 'sala de estar', 5),
('app/static/img/home-projects/construction/project-5/living-roomB.webp', 'sala de estar', 5),
('app/static/img/home-projects/construction/project-5/living-roomC.webp', 'sala de estar', 5),
('app/static/img/home-projects/construction/project-5/movie-theaterA.webp', 'sala de cine', 5),
('app/static/img/home-projects/construction/project-5/officeA.webp', 'despacho', 5),
('app/static/img/home-projects/construction/project-5/officeB.webp', 'despacho', 5),
('app/static/img/home-projects/construction/project-5/officeC.webp', 'despacho', 5),
('app/static/img/home-projects/construction/project-6/facadesA.webp', 'fachada', 6),
('app/static/img/home-projects/construction/project-6/garageA.webp', 'garaje', 6),
('app/static/img/home-projects/construction/project-6/garageB.webp', 'garaje', 6),
('app/static/img/home-projects/construction/project-6/garageC.webp', 'garaje', 6),
('app/static/img/home-projects/construction/project-6/laundry-roomA.webp', 'zona de lavado', 6),
('app/static/img/home-projects/construction/project-6/laundry-roomB.webp', 'zona de lavado', 6),
('app/static/img/home-projects/construction/project-6/laundry-roomC.webp', 'zona de lavado', 6),
('app/static/img/home-projects/construction/project-6/movie-theaterA.webp', 'sala de cine', 6),
('app/static/img/home-projects/construction/project-6/poolA.webp', 'piscina', 6),
('app/static/img/home-projects/construction/project-6/stairsA.webp', 'escaleras', 6),
('app/static/img/home-projects/construction/project-6/stairsB.webp', 'escaleras', 6),
('app/static/img/home-projects/construction/project-6/stairsC.webp', 'escaleras', 6);


INSERT INTO imagenes_proyectos (url, tipo, id_proyecto) VALUES 
('app/static/img/home-projects/reform/project-1/bathroomA.webp', 'baño', 7),
('app/static/img/home-projects/reform/project-1/bathroomB.webp', 'baño', 7),
('app/static/img/home-projects/reform/project-1/bathroomC.webp', 'baño', 7),
('app/static/img/home-projects/reform/project-1/facadesA.webp', 'fachada', 7),
('app/static/img/home-projects/reform/project-1/living-roomA.webp', 'sala de estar', 7),
('app/static/img/home-projects/reform/project-1/living-roomB.webp', 'sala de estar', 7),
('app/static/img/home-projects/reform/project-1/movie-theaterA.webp', 'sala de cine', 7),
('app/static/img/home-projects/reform/project-1/poolA.webp', 'piscina', 7),
('app/static/img/home-projects/reform/project-1/poolB.webp', 'piscina', 7),
('app/static/img/home-projects/reform/project-1/poolC.webp', 'piscina', 7),
('app/static/img/home-projects/reform/project-1/stairsA.webp', 'escaleras', 7),
('app/static/img/home-projects/reform/project-1/stairsB.webp', 'escaleras', 7),
('app/static/img/home-projects/reform/project-1/stairsC.webp', 'escaleras', 7),
('app/static/img/home-projects/reform/project-2/barbecue-areaA.webp', 'area de barbacoa', 8),
('app/static/img/home-projects/reform/project-2/barbecue-areaB.webp', 'area de barbacoa', 8),
('app/static/img/home-projects/reform/project-2/barbecue-areaC.webp', 'area de barbacoa', 8),
('app/static/img/home-projects/reform/project-2/living-roomA.webp', 'sala de estar', 8),
('app/static/img/home-projects/reform/project-2/living-roomB.webp', 'sala de estar', 8),
('app/static/img/home-projects/reform/project-2/patioA.webp', 'patio', 8),
('app/static/img/home-projects/reform/project-2/patioB.webp', 'patio', 8),
('app/static/img/home-projects/reform/project-2/patioC.webp', 'patio', 8),
('app/static/img/home-projects/reform/project-2/playgroundA.webp', 'patio de niños', 8),
('app/static/img/home-projects/reform/project-2/playgroundB.webp', 'patio de niños', 8),
('app/static/img/home-projects/reform/project-2/playgroundC.webp', 'patio de niños', 8),
('app/static/img/home-projects/reform/project-2/pondA.webp', 'estanque', 8),
('app/static/img/home-projects/reform/project-2/pondB.webp', 'estanque', 8),
('app/static/img/home-projects/reform/project-2/pondC.webp', 'estanque', 8),
('app/static/img/home-projects/reform/project-3/fenceA.webp', 'cerca', 9),
('app/static/img/home-projects/reform/project-3/fenceB.webp', 'cerca', 9),
('app/static/img/home-projects/reform/project-3/fenceC.webp', 'cerca', 9),
('app/static/img/home-projects/reform/project-3/kitchenA.webp', 'cocina', 9),
('app/static/img/home-projects/reform/project-3/kitchenB.webp', 'cocina', 9),
('app/static/img/home-projects/reform/project-3/kitchenC.webp', 'cocina', 9),
('app/static/img/home-projects/reform/project-3/movie-theaterA.webp', 'sala de cine', 9),
('app/static/img/home-projects/reform/project-3/movie-theaterB.webp', 'sala de cine', 9),
('app/static/img/home-projects/reform/project-3/movie-theaterC.webp', 'sala de cine', 9),
('app/static/img/home-projects/reform/project-3/officeA.webp', 'despacho', 9),
('app/static/img/home-projects/reform/project-3/officeB.webp', 'despacho', 9),
('app/static/img/home-projects/reform/project-3/officeC.webp', 'despacho', 9),
('app/static/img/home-projects/reform/project-4/bathroomA.webp', 'baño', 10),
('app/static/img/home-projects/reform/project-4/bathroomB.webp', 'baño', 10),
('app/static/img/home-projects/reform/project-4/bathroomC.webp', 'baño', 10),
('app/static/img/home-projects/reform/project-4/laundry-roomA.webp', 'zona de lavado', 10),
('app/static/img/home-projects/reform/project-4/laundry-roomB.webp', 'zona de lavado', 10),
('app/static/img/home-projects/reform/project-4/laundry-roomC.webp', 'zona de lavado', 10),
('app/static/img/home-projects/reform/project-4/living-roomA.webp', 'sala de estar', 10),
('app/static/img/home-projects/reform/project-4/living-roomB.webp', 'sala de estar', 10),
('app/static/img/home-projects/reform/project-4/living-roomC.webp', 'sala de estar', 10),
('app/static/img/home-projects/reform/project-4/roomA.webp', 'dormitorio', 10),
('app/static/img/home-projects/reform/project-4/roomB.webp', 'dormitorio', 10),
('app/static/img/home-projects/reform/project-4/roomC.webp', 'dormitorio', 10),
('app/static/img/home-projects/reform/project-5/gymA.webp', 'gym', 11),
('app/static/img/home-projects/reform/project-5/gymB.webp', 'gym', 11),
('app/static/img/home-projects/reform/project-5/gymC.webp', 'gym', 11),
('app/static/img/home-projects/reform/project-5/kitchenA.webp', 'cocina', 11),
('app/static/img/home-projects/reform/project-5/kitchenB.webp', 'cocina', 11),
('app/static/img/home-projects/reform/project-5/kitchenC.webp', 'cocina', 11),
('app/static/img/home-projects/reform/project-5/movie-theaterA.webp', 'sala de cine', 11),
('app/static/img/home-projects/reform/project-5/roomA.webp', 'dormitorio', 11),
('app/static/img/home-projects/reform/project-5/roomB.webp', 'dormitorio', 11),
('app/static/img/home-projects/reform/project-5/roomC.webp', 'dormitorio', 11),
('app/static/img/home-projects/reform/project-5/stairsA.webp', 'escaleras', 11),
('app/static/img/home-projects/reform/project-5/stairsB.webp', 'escaleras', 11),
('app/static/img/home-projects/reform/project-5/stairsC.webp', 'escaleras', 11);
