INSERT INTO traducciones(clave, es, en) VALUES
('nav_home', 'Home', 'Home'),
('nav_proyectos', 'Proyectos', 'Projects'),
('nav_nosotros', 'Nosotros', 'Us'),
('nav_servicios', 'Servicios', 'Services'),
('nav_contacto', 'Contacto', 'Contact'),
('nav_acceso', 'Acceso', 'Access'),
('frase_carrusel1', 'Transformamos tu hogar en el espacio de tus sueños', 'We transform your home into the space of your dreams'),
('frase_carrusel2', 'Construcción de calidad para un hogar lleno de momentos especiales', 'Quality construction for a home full of special moments'),
('frase_carrusel3', 'Hemos construido más de 100 casas con un éxito del 100%', 'We have built more than 100 houses with a 100% success rate'),
('frase_carrusel4', 'Diseñamos y construimos tu espacio perfecto, adaptado a tus necesidades', 'We design and build your perfect space, tailored to your needs'),
('frase_carrusel5', 'Transformamos cada proyecto en un hogar lleno de confort y estilo', 'We transform each project into a home full of comfort and style'),
('frase_carrusel6', 'Tu futuro hogar comienza con una visión. Nosotros lo hacemos posible', 'Your future home begins with a vision. We make it possible'),
('frase_carrusel7', 'Diseñamos y construimos espacios que reflejan tu estilo y comodidad', 'We design and build spaces that reflect your style and comfort'),
('frase_carrusel8', 'Construimos más que casas, creamos hogares llenos de felicidad', 'We build more than houses, we create homes full of happiness');

-- HOME SECTION
INSERT INTO traducciones(clave, es, en) VALUES
('home_cualidades_titulo', 'Nuestras cualidades', 'Our qualities'),
('home_cualidades_texto', 
'Disponemos de diseñadores, arquitectos y ingenieros con experiencia en el sector la construcción de casas y un gran equipo de obreros comprometidos ante cualquier proyecto',
'We have designers, architects and engineers with experience in the home construction sector and a great team of workers committed to any project'),
('home_cualidades_t1', 'Especialidades', 'Specialties'),
('home_cualidades_t2', 'Comunicación', 'Communication'),
('home_cualidades_t3', 'Personalización', 'Personalization'),
('home_cualidades_d1', 
'Cada integrante del equipo esta especializado en un sector como puede ser diseño de interiores diseño de exteriores, arquitectos especializados en casas rurales, modernas, clásicas... y obreros especializados en embaldosado, paredes, terrazas, jardinería...',
'Each team member specializes in a specific area, such as interior and exterior design. We have architects specializing in rural, modern, and classic homes... and we have workers specializing in tiling, walls, decking, and gardening...'),
('home_cualidades_d2',
'Tenemos constante comunicación con nuestros clientes, ya sea por medio de nuestro equipo de atención al cliente o con reuniones personales con nuestros ingenieros para recibir el feedback de nuestros clientes',
'We have constant communication with our customers, either through our customer service team or through personal meetings with our engineers to receive feedback from our customers'),
('home_cualidades_d3',
'Damos la oportunidad a nuestros clientes de dar forma a sus ideas teniendo en cuenta todos los requisitos y convertirlo en realidad además, también podemos ayudar con el asesoramiento de selección de terrenos para elegir la mejor opción',
'We give our clients the opportunity to shape their ideas taking into account all the requirements and turn it into reality. In addition, we can also help with land selection advice to choose the best option'),
('home_proceso_titulo', 'Nuestro proceso', 'Our process'),
('home_proceso_descripcion', 
'Nuestro equipo sigue un proceso de planificación preciso para la construcción de hogares, consiste en una serie de 3 pasos',
'Our team follows a precise planning process for building homes, consisting of a series of 3 steps'),
('home_proceso_t1', 'Reuniones y servicios', 'Meetings and services'),
('home_proceso_t2', 'Diseño y construcción', 'Design and construction'),
('home_proceso_t3', 'Dedicación y precisión', 'Dedication and precision'),
('home_proceso_d1',
'Comenzamos con una serie de reuniones donde anotamos todos los requisitos de nuestros clientes, estas reuniones pueden llevar hasta 2 meses, ya que, nos aseguramos de que se cumplan todos los requisitos para una mayor satisfacción de nuestros clientes y durante este tiempo estamos atentos ante cualquier cambio de idea',
"We begin with a series of meetings where we note down all of our client's requirements. These meetings can take up to two months, as we ensure that all requirements are met for greater customer satisfaction. During this time, we are attentive to any change of mind"),
('home_proceso_d2',
'Una vez que nuestro equipo de administración ya ha completado y reunido todos los requisitos lo mandamos a nuestro equipo arquitectos y ingenieros, donde ellos comienzan con el diseño de la casa, eligen los materiales óptimos para la construcción y realizan una maqueta de la casa que será presentada al cliente para dar el último visto bueno ',
'Once our management team has completed and gathered all the requirements, we forward it to our team of architects and engineers, where they begin designing the house, selecting the optimal materials for construction, and creating a mockup of the house, which will be presented to the client for final approval'),
('home_proceso_d3',
'Después comenzamos con nuestros ingenieros, aparejadores y obreros quienes comienzan la construcción de la obra a partir de los planos proporcionados por nuestros arquitectos, cada proyectos tiene asignado una serie de obreros que se dedicarán exclusivamente  al proyectos que tienen asignado garantizando que la curva sea continua y sin parones de obra',
'Then we start with our engineers, surveyors and workers who begin the construction of the work from the plans provided by our architects. Each project has a series of workers assigned who will be dedicated exclusively to the project they have assigned, ensuring that the curve is continuous and without work stops'),
('home_ultimos_proyectos_titulo', 'Últimos proyectos', 'Last projects');

-- PROJECT SECTION
-- important order of every type/category
INSERT INTO traducciones(clave, es, en) VALUES
('proyecto_titulo', 'Sección de nuestros proyectos', 'Our section projects'),
('proyecto_descripcion', 
'Disponemos de un buen historial  de proyectos que hemos realizado a lo largo de los años, nos encargamos de piscinas, cocinas, dormitorios, garajes...',
"We have a good track record of projects over the years. We've worked on swimming pools, kitchens, bedrooms, garages, and more"),
('proyecto_interiores', 'Interiores', 'Interiors'), 
('proyecto_interiores_1', 'Salas de estar', 'living rooms'), -- 1
('proyecto_interiores_2', 'Cocinas', 'Kitchens'), -- 2
('proyecto_interiores_3', 'Dormitorios', 'Bedrooms'), -- 3
('proyecto_interiores_4', 'Baños', 'Bathrooms'), -- 4
('proyecto_interiores_5', 'Escaleras', 'Stairs'), -- 5
('proyecto_interiores_6', 'Despachos', 'Offices'), -- 6
('proyecto_interiores_7', 'Gimnasios', 'Gyms'), -- 7
('proyecto_interiores_8', 'Salas de cine', 'Home theaters'), -- 8
('proyecto_interiores_9', 'Zonas de lavado', 'Laundry room'), -- 9
('proyecto_exteriores', 'Exteriores', 'Exteriors'),
('proyecto_exteriores_1', 'Fachadas', 'Facades'), -- 10
('proyecto_exteriores_2', 'Terrazas', 'Terraces'), -- 11
('proyecto_exteriores_3', 'Piscinas', 'Pools'), -- 12
('proyecto_exteriores_4', 'Garajes', 'Garages'), -- 13
('proyecto_exteriores_5', 'Cercas', 'Fences'), -- 14
('proyecto_exteriores_6', 'Patios', 'Patios'), -- 15
('proyecto_exteriores_7', 'Zona barbacoas', 'BBQ area'), -- 16 
('proyecto_exteriores_8', 'Estanques', 'Ponds'), -- 17
('proyecto_exteriores_9', 'Patio de niños', 'Playground'); -- 18

-- DESCRIPTION FOR EVERY PROJECT
INSERT INTO traducciones(clave, es, en, id_proyecto) VALUES
('descripcion_general_p1_t1',
'Ubicada frente al mar, esta casa moderna destaca por su fachada blanca y líneas limpias que se integran con el entorno natural. Rodeada por cercas de madera, combina calidez y estilo contemporáneo desde el primer vistazo.',
'Located by the sea, this modern house stands out for its white facade and clean lines that blend seamlessly with the natural surroundings. Surrounded by wooden fences, it combines warmth and contemporary style from the very first glance.',
1),
('descripcion_general_p1_t2',
'En el interior, la vivienda cuenta con tres salas de estar con suelos de madera y paredes blancas, diseñadas para aprovechar al máximo la luz natural. Los sofás de estilo moderno, en tonos neutros, crean espacios cómodos y elegantes.',
'Inside, the home features three living rooms with wooden floors and white walls, designed to make the most of natural light. Modern-style sofas in neutral tones create comfortable and elegant spaces.',
1),
('descripcion_general_p1_t3',
'Dispone de cuatro dormitorios que siguen el mismo estilo: madera clara, blanco predominante y un ambiente tranquilo pensado para el descanso. Las dos escaleras de madera, con un diseño moderno y barandillas de vidrio, conectan los distintos niveles de la casa con ligereza y fluidez.',
'There are four bedrooms that follow the same design: light wood, a predominant white palette, and a calm atmosphere designed for rest. Two wooden staircases with modern design and glass railings connect the different levels of the house with lightness and fluidity.',
1),
('descripcion_general_p1_t4',
'El proyecto se completa con tres terrazas frente al mar, cada una equipada con mesas de madera ideales para disfrutar del paisaje en un entorno relajado y moderno.',
'The project is completed by three sea-facing terraces, each equipped with wooden tables—ideal for enjoying the scenery in a relaxed, modern setting.',
1),
('descripcion_general_p2_t1',
'Esta impresionante vivienda moderna combina diseño vanguardista y funcionalidad en una ubicación privilegiada frente al mar. Su fachada contemporánea, junto a una cerca metálica negra, crea una imagen sofisticada desde el exterior',
'This stunning modern home blends cutting-edge design with functionality in a privileged seaside location. Its contemporary facade, paired with a sleek black metal fence, offers an elegant and sophisticated presence from the outside.',
2),
('descripcion_general_p2_t2',
'La casa cuenta con una amplia piscina, perfecta para relajarse disfrutando del entorno. En el interior, destacan dos baños modernos con acabados en blanco y negro, líneas limpias y materiales de alta calidad.',
'The property features a spacious swimming pool, ideal for relaxing while enjoying the coastal surroundings. Inside, it includes two modern bathrooms with high-end finishes in black and white, emphasizing clean lines and minimalist style.',
2),
('descripcion_general_p2_t3',
'Dispone de dos garajes privados y dos gimnasios integrados en la vivienda, ambos con vistas directas al mar a través de grandes ventanales de cristal que inundan los espacios de luz natural.',
'The house also offers two private garages and two fully equipped gyms, both with breathtaking sea views through expansive floor-to-ceiling glass panels that flood the interiors with natural light.',
2),
('descripcion_general_p2_t4',
'El entretenimiento está garantizado gracias a una sala de cine privada, ideal para disfrutar del confort sin salir de casa. El proyecto se completa con una elegante terraza equipada con butacas blancas y suelo negro, que aporta contraste y estilo en un ambiente único frente al océano.',
'Entertainment is elevated with a private home cinema, perfect for enjoying movies in total comfort. The design is completed with a stylish terrace featuring white lounge chairs and a black floor, creating a bold, modern contrast in a unique oceanfront setting.',
2),
('descripcion_general_p3_t1',
'Ubicada en un entorno natural rodeado de árboles, esta encantadora casa de estilo rústico combina calidez y carácter en cada rincón. Su fachada en madera, realzada por dos pilares de piedra en la entrada, marca una bienvenida elegante y acogedora.',
'Set in a peaceful forest setting, this charming rustic-style home blends warmth and character throughout. The wooden facade, highlighted by two stone pillars at the entrance, creates an elegant and welcoming first impression.',
3),
('descripcion_general_p3_t2',
'El diseño rústico se extiende a los espacios exteriores, donde destacan dos áreas de barbacoa con suelos de piedra, ideales para reuniones al aire libre en armonía con el paisaje del bosque.',
'The rustic style continues outdoors with two barbecue areas, both featuring stone flooring and a design that harmonizes perfectly with the natural surroundings.',
3),
('descripcion_general_p3_t3',
'En el interior, la casa cuenta con tres zonas de lavado, todas con suelos de madera y equipadas con muebles y lavadoras blancas, combinando funcionalidad con estética cálida y natural.',
'Inside, the home offers three laundry rooms, each with wooden floors and equipped with white cabinets and washing machines, combining practicality with a cozy aesthetic.',
3),
('descripcion_general_p3_t4',
'El amplio patio trasero incluye zonas pavimentadas en piedra y otras en madera, donde se han dispuesto sillones para disfrutar del aire libre. El conjunto se completa con un gran estanque, perfecto para peces y para añadir un elemento de serenidad al entorno.',
'The spacious backyard features a mix of stone and wooden flooring, with comfortable lounge seating perfect for relaxing in nature. A large pond adds a serene touch and can host fish, enhancing the connection with the environment.',
3),
('descripcion_general_p4_t1',
'Esta casa moderna ubicada en la costa combina el uso de piedra natural con un diseño en tonos blancos que resalta por su elegancia y conexión con el entorno marítimo. Su estilo limpio y contemporáneo convierte cada espacio en una experiencia visual y funcional.',
'This stunning modern home on the coast combines natural stone with a clean white aesthetic, offering an elegant and contemporary design perfectly integrated with the seaside landscape.',
4),
('descripcion_general_p4_t2',
'El interior cuenta con dos salas de estar modernas: una equipada con televisor para el entretenimiento, y otra diseñada como espacio abierto para la relajación. Ambas comparten un diseño minimalista con paredes blancas y una atmósfera luminosa.',
'The interior features two modern living rooms—one with a TV for entertainment and the other designed as a serene, open space. Both rooms have white walls and a bright, minimalist atmosphere.',
4),
('descripcion_general_p4_t3',
'En la parte trasera, la casa ofrece dos patios infantiles con césped artificial, columpios y toboganes, ideales para el disfrute seguro de los más pequeños. El paisaje exterior se realza con tres fuentes modernas con peces, que aportan movimiento y serenidad al ambiente.',
"At the back of the property, you'll find two dedicated children's play areas with artificial grass, swings, and slides, providing safe and fun outdoor spaces. The garden is further enhanced by three modern fountains with fish, adding life and tranquility.",
4),
('descripcion_general_p4_t4',
'La propiedad incluye dos piscinas traseras, perfectas para el disfrute familiar o social, todas con vistas al mar. Finalmente, la casa dispone de tres terrazas modernas, dos de ellas abiertas y una cubierta, ofreciendo diferentes opciones para disfrutar de las vistas y la brisa marina en cualquier momento del día.',
'The house includes two rear swimming pools, ideal for family fun or relaxation, all with direct sea views. It also features three modern terraces—one covered and two open-air, perfect for enjoying the ocean breeze at any time of day.',
4),
('descripcion_general_p5_t1',
'Esta elegante casa de estilo clásico se presenta con una fachada en tono amarillo suave y un tejado gris oscuro, evocando una estética tradicional y cálida.',
'This refined classic-style home features a soft yellow facade and a dark gray roof, offering a warm and timeless exterior.',
5),
('descripcion_general_p5_t2',
'En el interior, destacan dos gimnasios privados, ambos con suelos de madera, paredes marrones y techos blancos, creando espacios acogedores para el entrenamiento diario. La vivienda también cuenta con dos cocinas funcionales y modernas, con suelos de madera, muebles inferiores negros y superficies superiores blancas, logrando un equilibrio visual entre lo clásico y lo contemporáneo.',
'Inside, the property includes two private gyms with wooden floors, brown walls, and white ceilings, creating cozy yet functional workout spaces. The home also boasts two kitchens with wooden flooring, black lower cabinets, and white upper surfaces, combining traditional style with modern touches.',
5),
('descripcion_general_p5_t3',
'Las tres salas de estar mantienen el mismo suelo de madera, con una de las paredes en tono marrón y el resto en blanco, generando contraste sin perder la armonía clásica del diseño.',
'There are three living rooms, each with wooden floors and a mix of brown and white walls, adding depth and contrast while maintaining a harmonious atmosphere.',
5),
('descripcion_general_p5_t4',
'Para el entretenimiento, la casa incluye una sala de cine privada, perfecta para disfrutar del cine en casa con total comodidad. Además, dispone de tres despachos elegantes, todos con suelos y mobiliario de madera clásica y paredes marrones, ideales para trabajar o estudiar en un entorno cálido y profesional.',
'For leisure, the house features a private cinema room, offering the perfect setting for home entertainment. It also includes three home offices, all designed with classic wooden floors and furniture and brown walls, ideal for working or studying in a warm, elegant environment.',
5),
('descripcion_general_p6_t1',
'Ubicada en lo alto de una colina, esta casa moderna destaca por su diseño limpio y su fachada blanca, ofreciendo vistas despejadas y una sensación de amplitud en cada rincón.',
'Perched on a hill, this sleek modern home features a clean white facade and stunning open views, designed to maximize space and light.',
6),
('descripcion_general_p6_t2',
'La propiedad cuenta con dos garajes modernos para coches, integrados de forma elegante en la estructura. En el interior, dispone de dos zonas de lavado totalmente en color blanco, manteniendo la estética minimalista y ordenada de la vivienda.',
'The property includes two modern car garages, seamlessly integrated into the architecture. Inside, it offers two all-white laundry rooms, maintaining a minimalist and cohesive interior design.',
6),
('descripcion_general_p6_t3',
'Para el entretenimiento, la casa incluye una sala de cine privada acompañada de una mesa de billar, creando un espacio versátil para disfrutar en familia o con amigos.',
'Entertainment is a highlight, with a private home cinema and a billiards table, creating the perfect space for relaxation and fun.',
6),
('descripcion_general_p6_t4',
'En el exterior, una piscina con bordes de cristal ofrece una experiencia visual única, fusionándose con el entorno natural. Además, la vivienda cuenta con tres escaleras de madera modernas, combinando tonos blancos y marrón oscuro, que conectan los distintos niveles con estilo y ligereza visual.',
'Outdoors, a glass-edged swimming pool provides a striking visual effect, blending seamlessly with the natural surroundings. The home also features three modern wooden staircases, combining white and dark brown tones, adding elegance and contrast throughout the living spaces.',
6),
('descripcion_general_p7_t1',
'Ubicada en plena naturaleza, esta casa rústica de madera en las montañas ofrece un refugio cálido y acogedor, combinando materiales nobles y diseño tradicional.',
'Nestled in the heart of nature, this rustic wooden mountain home offers a warm and inviting retreat, blending natural materials with classic design.',
7),
('descripcion_general_p7_t2',
'Cuenta con un baño elegante, revestido en cerámica blanca y equipado con muebles en madera oscura, que contrastan con delicadeza y aportan carácter al espacio.',
'The house features a stylish bathroom with white ceramic finishes and dark wooden furniture, creating a refined contrast and a cozy atmosphere.',
7),
('descripcion_general_p7_t3',
'La vivienda dispone de dos salas de estar: una con suelo de madera y paredes marrones, ideal para disfrutar de una atmósfera cálida, y otra también con suelo de madera pero cubierta con alfombras y paredes blancas, ofreciendo un ambiente más suave y luminoso.',
'It includes two living rooms: one with wooden floors and brown walls, ideal for a warm, earthy ambiance, and the other also with wooden flooring, but covered with rugs and featuring white walls, offering a softer and brighter environment.',
7),
('descripcion_general_p7_t4',
'Incluye además una sala de cine completamente revestida en madera, equipada con sillones en tono marrón madera, perfecta para disfrutar del entretenimiento en un entorno rústico y cómodo.',
'A private home cinema, fully lined in wood and equipped with brown wooden-tone armchairs, provides a cozy space for entertainment in a rustic setting.',
7),
('descripcion_general_p7_t5',
'En el exterior, destacan tres piscinas rodeadas de estructuras de madera, integradas con el paisaje y pensadas para el descanso. Una escalera clásica de madera conecta los distintos niveles de la casa, aportando continuidad al diseño cálido y natural del proyecto.',
'Outdoors, the property boasts three pools, each surrounded by wooden decking, harmonizing beautifully with the mountain landscape. A classic wooden staircase connects the different levels of the home, continuing the natural, warm aesthetic throughout the house.',
7),
('descripcion_general_p8_t1',
'Ubicada en un entorno montañoso y rodeada de naturaleza, esta casa de estilo rústico ha sido diseñada para combinar confort moderno con materiales tradicionales.',
'Set in the mountains and surrounded by nature, this rustic-style home blends modern comfort with traditional materials in a warm and inviting setting.',
8),
('descripcion_general_p8_t2',
'Cuenta con tres áreas de barbacoa, todas con suelo de piedra y techos de madera, ideales para reuniones al aire libre protegidas y acogedoras.',
'The property features three barbecue areas, each with stone flooring and wooden roofs, offering cozy outdoor spaces perfect for entertaining year-round.',
8),
('descripcion_general_p8_t3',
'En el interior, la casa ofrece dos salas de estar con suelos de madera, alfombras negras y sofás modernos, que crean un equilibrio entre el estilo rústico y el diseño contemporáneo.',
'Inside, the home includes two living rooms with wooden floors, black rugs, and modern sofas, striking a balance between rustic warmth and contemporary design.',
8),
('descripcion_general_p8_t4',
'El espacio exterior incluye un patio mixto de madera y tierra, equipado con butacas y sillones de madera, perfecto para relajarse en contacto con el entorno. Además, la vivienda dispone de un patio infantil con suelo de tierra y juegos construidos en madera, como casitas, toboganes y estructuras para trepar.',
"Outside, there's a patio with wooden and earth flooring, furnished with wooden lounge chairs and seating, ideal for relaxing in a natural atmosphere. A dedicated children’s play area features earth flooring and wooden playhouses, slides, and climbing structures—all crafted in harmony with the environment.",
8),
('descripcion_general_p8_t5',
'Como toque final, el terreno cuenta con estanques de piedra en forma circular, que aportan serenidad y un vínculo natural con el paisaje montañoso.',
'Completing the outdoor space are circular stone ponds, adding a peaceful, organic element to the mountainous landscape.',
8),
('descripcion_general_p9_t1',
'Esta casa moderna destaca por su diseño audaz y elegante, combinando materiales contemporáneos y una paleta de colores contrastante. El exterior está delimitado por cercas de metal negro con detalles en madera, aportando seguridad y estilo desde el primer vistazo.',
'This modern home stands out for its bold, elegant design that blends contemporary materials with a striking color palette. The exterior is framed by black metal fences accented with wood, providing both style and security.',
9),
('descripcion_general_p9_t2',
'La vivienda cuenta con tres cocinas, todas con un diseño uniforme: techos y suelos blancos, paredes negras y mobiliario negro, creando un ambiente moderno, minimalista y sofisticado.',
'Inside, the property features three kitchens, all sharing the same sophisticated layout: white floors and ceilings, black walls, and black cabinetry, creating a minimalist and high-contrast visual appeal.',
9),
('descripcion_general_p9_t3',
'El mismo estilo se traslada a la sala de cine, que replica el formato visual de las cocinas, ofreciendo un espacio envolvente y con fuerte carácter visual.',
'The home cinema follows the same design concept, offering a dramatic and immersive entertainment space.',
9),
('descripcion_general_p9_t4',
'La casa también incluye un despacho con suelo de cerámica en tono negro suave, paredes negras y un techo blanco, con vistas directas al mar, ideal para trabajar en un entorno elegante y tranquilo.',
'A home office completes the layout, featuring soft black ceramic flooring, black walls, and a white ceiling, with direct ocean views—a perfect balance between focus and serenity.',
9),
('descripcion_general_p10_t1',
'Esta casa de estilo clásico se caracteriza por su diseño coherente en todos los espacios, combinando calidez y serenidad en cada rincón.',
'This classic-style home features a cohesive design throughout, combining warmth and serenity in every space.',
10),
('descripcion_general_p10_t2',
'Cuenta con tres baños, todos decorados con un estilo clásico que incluye suelos de madera, paredes en azul claro y techos blancos, creando ambientes luminosos y relajantes.',
'It includes three bathrooms, each designed with wooden flooring, light blue walls, and white ceilings, creating bright and calming environments.',
10),
('descripcion_general_p10_t3',
'El mismo diseño se extiende a tres zonas de lavado, manteniendo la armonía estética con acabados idénticos a los de los baños.',
'The home also offers three laundry rooms, matching the same aesthetic for a unified interior look.',
10),
('descripcion_general_p10_t4',
'La vivienda incluye además tres salas de estar y tres dormitorios, todos siguiendo la misma línea de diseño: suelos de madera, paredes azul claro y techos blancos, generando una continuidad visual y un ambiente acogedor en toda la casa.',
'Additionally, it features three living rooms and three bedrooms, all sharing the same classic design elements: wooden floors, light blue walls, and white ceilings, providing visual continuity and a cozy, timeless atmosphere.',
10),
('descripcion_general_p11_t1',
'Esta casa moderna ubicada en el campo destaca por su diseño limpio y minimalista, con una fachada completamente blanca que resalta en el entorno natural.',
'This modern countryside home features a fully white exterior, standing out elegantly in its natural surroundings.',
11),
('descripcion_general_p11_t2',
'En su interior alberga dos gimnasios privados, ambos con vistas al campo, ideales para entrenar en un ambiente tranquilo y natural.',
'Inside, it offers two private gyms with open views of the countryside, perfect for peaceful and focused workouts.',
11),
('descripcion_general_p11_t3',
'La vivienda cuenta con tres cocinas modernas, todas con un estilo completamente blanco: suelos, paredes, techos y mobiliario, ofreciendo un entorno elegante y uniforme.',
'The house includes three modern kitchens, all designed entirely in white—from the flooring and walls to the ceiling and cabinetry—creating a sleek and cohesive visual flow.',
11),
('descripcion_general_p11_t4',
'Dispone además de una sala de cine moderna, perfectamente integrada al diseño contemporáneo del hogar, pensada para el entretenimiento en casa.',
'A modern home cinema adds a touch of luxury and comfort, ideal for in-home entertainment.',
11),
('descripcion_general_p11_t5',
'Las tres habitaciones principales están conectadas a pequeñas terrazas a través de puertas de cristal, lo que permite la entrada de luz natural y una conexión directa con el exterior.',
'Each of the three main bedrooms connects to a small terrace through glass doors, enhancing natural light and outdoor access.',
11),
('descripcion_general_p11_t6',
'Completan el proyecto tres escaleras modernas de madera, que aportan calidez y contraste al diseño general blanco de la casa.',
'The home is completed with three modern wooden staircases, adding warmth and contrast to the otherwise all-white interior.',
11);

-- US SECTION
INSERT INTO traducciones(clave, es, en) VALUES
('nosotros_1_titulo', 'Quienes somos', 'Who we are'),
('nosotros_1_descripcion1', 
'Somos un equipo de profesionales decididos y dedicados a cumplir nuestros objetivos
y dar vida a las ideas que se nos proponen junto con nuestro equipo',
'We are a team of determined professionals dedicated to achieving our goals and 
bringing to life the ideas proposed to us along with our team'),
('nosotros_1_descripcion2',
'En EloyCon, llevamos más de 15 años construyendo sueños. Nos especializamos en el diseño y la construcción de viviendas 
personalizadas, ofreciendo soluciones integrales que combinan calidad, eficiencia y compromiso.
Creemos que cada proyecto es único, por eso trabajamos mano a mano con nuestros clientes para transformar sus ideas 
en hogares funcionales, estéticos y duraderos. Desde la planificación hasta la entrega final, 
nos encargamos de todo el proceso con un equipo altamente capacitado y materiales de primera calidad',
"At EloyCon, we've been building dreams for over 15 years. We specialize in the design and construction of custom homes, 
offering comprehensive solutions that combine quality, efficiency, and commitment. We believe each project is unique, 
which is why we work closely with our clients to transform their ideas into functional, aesthetic, and long-lasting homes. 
From planning to final delivery, we manage the entire process with a highly trained team and top-quality materials"),
('nosotros_1_descripcion3',
'Nuestra misión es construir espacios que mejoren la vida de las personas, cuidando cada detalle y respetando siempre los plazos y 
presupuestos acordados. Si buscas confianza, profesionalismo y resultados que superen tus expectativas, estás en el lugar correcto',
"Our mission is to build spaces that improve people's lives, taking care of every detail and always respecting agreed deadlines and 
budgets. If you're looking for trust, professionalism, and results that exceed your expectations, you've come to the right place."),
('nosotros_2_titulo', 'Nuestra historia', 'Our history'),
('nosotros_2_d1', 
'Nacimos como un pequeño equipo de profesionales apasionados por la arquitectura y la construcción. Comenzamos con reformas y obras menores, siempre priorizando la calidad y la satisfacción del cliente',
'We started as a small team of professionals passionate about architecture and construction. Our early projects focused on renovations and small-scale works, always prioritizing quality and client satisfaction'),
('nosotros_2_d2',
'Nos consolidamos en el sector con la construcción de nuestras primeras viviendas unifamiliares. Incorporamos nuevas tecnologías y ampliamos nuestro equipo técnico, lo que nos permitió asumir obras de mayor envergadura',
'We gained a solid foothold in the industry with our first custom home builds. With new technologies and an expanded technical team, we began taking on larger and more ambitious construction projects'),
('nosotros_2_d3',
'En plena pandemia, apostamos por la innovación. Digitalizamos procesos, reforzamos nuestra presencia online y comenzamos a trabajar en proyectos de construcción sostenible y eficiencia energética',
'Amid the pandemic, we embraced innovation. We digitalized processes, strengthened our online presence, and started developing sustainable construction projects focused on energy efficiency'),
('nosotros_2_d4',
'Hoy somos una empresa referente en el sector, con más de 100 proyectos entregados. Seguimos creciendo con el mismo compromiso de siempre: construir espacios que mejoran la vida de las personas, cuidando cada detalle',
'Today, we are a leading company in the construction sector, with over 100 completed projects. We continue to grow with the same commitment as always: to build spaces that improve people’s lives, paying close attention to every detail'),
('nosotros_3_titulo', 'Nuestro equipo', 'Our team'),
('nosotros_3_t1', 'Líderes de empresa', 'Leadership team'),
('nosotros_3_t2', 'Arquitectos e ingenieros', 'Architects and engineers'),
('nosotros_3_t3', 'Equipo general', 'Core team'),
('nosotros_4_titulo', 'Responsabilidad social corporativa', 'Corporate Social Responsibility'),
('nosotros_4_t1', 'Sostenibilidad ambiental', 'Environmental sustainability'),
('nosotros_4_t2', 'Seguridad y bienestar laboral', 'occupational safety and well-being'),
('nosotros_4_t3', 'Compromiso con la comunidad', 'commitment to the community'),
('nosotros_4_t4', 'Ética y transparencia', 'Ethics and transparency'),
('nosotros_4_d1', 
'Trabajamos con una firme política de gestión responsable de los recursos, priorizando el uso de materiales sostenibles y fomentando la eficiencia 
energética en cada proyecto. Implementamos prácticas orientadas a la reducción de residuos y a la correcta gestión de los mismos, minimizando el impacto ambiental de nuestras obras',
'We operate with a firm policy of responsible resource management, prioritizing the use of sustainable materials and promoting energy efficiency in every project. We implement 
practices aimed at reducing and properly managing waste, minimizing the environmental impact of our projects'),
('nosotros_4_d2',
'Nuestro equipo humano es nuestro principal valor. Por ello, garantizamos las condiciones óptimas de seguridad en obra y promovemos programas de formación continua en prevención 
de riesgos laborales, con el objetivo de asegurar un entorno de trabajo seguro y responsable',
'Our team is our greatest asset. Therefore, we guarantee optimal safety conditions on site and promote ongoing training programs in occupational risk prevention, with the goal 
of ensuring a safe and responsible work environment'),
('nosotros_4_d3',
'Creemos en el desarrollo local y en el fortalecimiento de las comunidades donde trabajamos. Colaboramos activamente con proveedores, profesionales y mano de obra local, 
contribuyendo así al crecimiento económico de nuestro entorno',
'We believe in local development and strengthening the communities where we work. We actively collaborate with local suppliers, professionals, and labor, thus contributing 
to the economic growth of our surrounding communities'),
('nosotros_4_d4',
'Basamos nuestra actividad en principios éticos y de transparencia, manteniendo una comunicación clara, honesta y directa con nuestros clientes, proveedores y colaboradores, 
garantizando así relaciones de confianza y largo plazo',
'We base our activities on ethical principles and transparency, maintaining clear, honest, and direct communication with our clients, suppliers, and collaborators, 
thus ensuring long-term, trusting relationships'); 

-- FOOTER
INSERT INTO traducciones(clave, es, en) VALUES
('footer1_1_titulo', 'Información de contacto', 'Contact information'),
('footer1_1_c1', 'Calle Montenegro, num 43, piso 12', 'Montenegro Street, number 43, 12th floor'),
('footer1_1_c2', 'Palma, Islas Baleares', 'Palma, Balearic Islands'),
('footer1_1_c3', 'info@eloycon.con', 'info@eloycon.con'),
('footer1_1_c4', '645 34 65 23', '645 34 65 23'),
('footer1_3_d', 'Ponte en contacto directamente con nosotros por medio de un WhatsApp para poder conversar sobre tus futuras ideas', 'Contact us directly via WhatsApp so we can discuss your future ideas'),
('footer2', '© EloyCon 2025 · Visite nuestra política de privacidad y política de cookies', '© EloyCon 2025 · Visit our privacy policy and cookie policy');